# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'Tiny Test'
tagline:             'A project blog'
description:         'A notes area for this project. Something to just write thoughts on and come back to later. '
url:                 'http://abrahamvarricatt.github.io/tiny_test'
baseurl:             '/tiny_test'
paginate:            5

# About/contact
author:
  name:              Abraham V.
  url:               https://twitter.com/chronodekar
  email:             notnow@email.com

# Custom vars
version:             1.0.0
